require "android_studio"

workspace "android_studio_example"
	configurations { "Debug", "Release" }
	gradleversion "com.android.tools.build:gradle:3.5.0-beta01"
	androidsdkversion "28"
	androidminsdkversion "25"
	location ("android")

project "app"
	kind "ConsoleApp"
	language "C++"
	targetdir "bin/%{cfg.buildcfg}"

	-- We don't need to add any assetdirs. however, this is a bug in premake android-studio module,
	-- which requires adding an assetdirs section to accept androidmanifest section.
	assetdirs
	{
		"manifest"
	}

	-- Use an existing manifest, rather than generating a manifest. The manifest generated by the premake
	-- android-studio module does not have an activity, and therefore cannot be started.
	androidmanifest "manifest/AndroidManifest.xml"

	files 
	{ 
		"cpp/**.*", 
		"java/**.*",
		"manifest/**.*"
	}
	
	links
	{
		"log" -- required for c++ logging	
	}
	
	buildoptions
	{
		"-std=c++11" -- flag mainly here to test cmake compile options
	}
	
	linkoptions
	{
		"--no-undefined" -- this flag is used just to cmake link libraries
	}
	
	includedirs
	{
		"h"
	}
	
	androidabis
	{
		"armeabi-v7a", "x86"
	}
	
	configuration "Debug"
		defines { "DEBUG" }
		symbols "On"

	configuration "Release"
		defines { "NDEBUG" }
		optimize "On"
